### ISSUE TITLE
Add banner above Game Log to show that obserever is running

### ISSUE THREAD

**Issue by PanoramicPanda** [PanoramicPanda/ddb_observeGameLog#10]
Adding a banner (above the ol) to show that Observer is running.

- Get extras in manifest:
```
  "environment": {
    "extras": [
      "fonts",
      "colorStyles"
    ]
```
- Use TS Font family (`OptimusPrinceps`) for banner
- Use ddbo.png within banner
- Text something along the lines of <ddbo.png> "Now observing log"
- Centered text
- Update landing page readme to state that the banner will show up once the Symbiote is doing its job

**Comment by PanoramicPanda** [comment]
- only add banner when everything is successful (Hook, darkmode, decimate)

**Comment by PanoramicPanda** [comment]
Inject in similar ways to example symbiote: https://github.com/Bouncyrock/symbiotes-examples/blob/main/Website_Viewer/myCustomInjectedScript.js

**Comment by asaurb** [comment]
Currently working on an implementation of this as of yesterday. (My fork of the repo is not 100% pushed to my current progress)

Done:
* [x] Cosmetics:
  * [x] Injected local html shows up in iframe as banner
  * [x] Added text (Now observing log...)
  * [x] Horizontally centered
  * [x] Vertically centered (It is close but not perfect)
  * [x] Correct font
  * [x] ddb observer logo
  * [x] Version bump to v1.0.8
  * [x] Changelog annotated w/v1.0.8 changes
* [x] Functional:
  * [x] Logic checks both observer is running and log is expanded
  * [x] Banner visibility/behavior on logic state
  * [x] Fullscreen log occasional failure to load/expand fix
    * JS now waits for TS API to initialize
    * JS now continuously checks that log and all parent objects are on page before manipulating after button press
* [x] Wishlist:
  * [x] Smooth banner transition for symbiote state (drop-in/drop out animation)
  * [x] Nicer looking scrollbar. Something modern... maybe like the github one?

Obviously tweak the cosmetics to your liking. If you make a branch for this issue I will PR it over to that separate branch away from main if you want to play with what I've got later

**Comment by PanoramicPanda** [comment]
Created https://github.com/PanoramicPanda/ddb_observeGameLog/tree/feature/banner branch. If you do a PR to that I can check it out and tinker over the weekend. I'll be sure to include you on any PR requests to main.

**Comment by PanoramicPanda** [comment]
Completed by #20
