### ISSUE TITLE
Game Log Structure Update

### ISSUE THREAD

**Issue by PanoramicPanda** [PanoramicPanda/ddb_observeGameLog#21]
Seems D&D Beyond has updated the structure of the Game Log. Need to update the scan and grab to accommodate whatever the new structure is.

**Comment by asaurb** [comment]
I'll take a look at it. Confirmed the same bug on my chrome extension version. It must've happened this week, as it worked as of Saturday, 10 Aug 24

**Comment by asaurb** [comment]
Ok, so the basic functionality works if you modify one line https://github.com/PanoramicPanda/ddb_observeGameLog/blob/3af6f3ef20b93b51188679476a72c8fc1d6d7486/fullscreen_log.js#L44

Replace it with
`if (element.className.includes("gamelog-button")) {`

I will continue to hunt for how to fix the CSS. I am not familiar with webdev or even JS for that matter so I am struggling to find the CSS that references the list items in the roll log. I will keep looking.
