### ISSUE TITLE
Missing rolls from chatlog

### ISSUE THREAD

**Issue by Fathomb** [PanoramicPanda/ddb_observeGameLog#3]
I've installed and have DnD beyond open in the symbiotes panel but the dice rolls do no appear in the Talespire chat log

**Comment by PanoramicPanda** [comment]
Did you navigate to a Campaign, and open the Game Log within the Symbiote?

Do you have any other Symbiotes running in the background? (This shouldn't be an issue, but checking anyway).

**Comment by PanoramicPanda** [comment]
@Fathomb Given all the updates we've had, I'm curious if this works for you now. Be sure you're going into the Symbiote panel and checking for updates. The Symbiote should be on v1.0.7 by now. You'll be able to see the current version in the top-right of the landing page before going to D&D Beyond.

**Comment by Fathomb** [comment]
I got it to work, thanks :). My mistake was opening my character sheet instead of opening the Game Log first.
