### ISSUE TITLE
White Screen of Death

### ISSUE THREAD

**Issue by Madzapple** [PanoramicPanda/ddb_observeGameLog#5]
As I sign into dndbeyong, via the Symbiote (with no other symbiote running), I am then faced with a blank white screen.  I have not been able to get further than this.

**Comment by PanoramicPanda** [comment]
That is an odd one. I know it seems obvious, but a screenshot would be cool if you can get one.

First thought - what OS are you running?
Second thought - if I ask you to check out the Symbiote Debug and Dev Console for it, would you know how to get there?

**Comment by PanoramicPanda** [comment]
@Madzapple Given all the updates we've had, I'm curious if this works for you now. Be sure you're going into the Symbiote panel and checking for updates. The Symbiote should be on v1.0.8 by now. You'll be able to see the current version in the top-right of the landing page before going to D&D Beyond.

**Comment by Madzapple** [comment]
I am using Windows.
I just did the update and its the same situation.  v1.0.8
I'm signing into dndbeyond using a google account from within the symbiote browser.
When I click sign in with the google account I get the white screen of death.
![image](https://github.com/PanoramicPanda/ddb_observeGameLog/assets/73278600/4d157528-a032-4278-9ce6-9b0884f01d58)

**Comment by PanoramicPanda** [comment]
Ah, that's likely your issue then.

Symbiotes are currently being detected as a not supported browser by some login methods. They also do not support pop-up logins such as Google. Logging in with a Wizard's account seems to be the most successful way at the moment. This will hopefully be resolved in the future by TaleSpire.
